language: java
install: skip
dist: trusty
jdk: oraclejdk8

env:
  - OSSRH_USER=stub OSSRH_PASS=stub

script:
  - ./gradlew build --info

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/