const val RELEASE_USER = "hendraanggrian"
const val RELEASE_GROUP = "com.$RELEASE_USER"
const val RELEASE_ARTIFACT = "javapoet-ktx"
const val RELEASE_VERSION = "0.8"
const val RELEASE_DESC = "JavaPoet Kotlin extension"
const val RELEASE_WEB = "https://github.com/$RELEASE_USER/$RELEASE_ARTIFACT"
