const val VERSION_GRADLE = "5.6"
const val VERSION_KOTLIN = "1.3.41"

internal const val VERSION_JAVAPOET = "1.11.1"
internal const val VERSION_DOKKA = "0.9.18"
internal const val VERSION_BINTRAY = "1.8.4"
internal const val VERSION_BINTRAY_RELEASE = "0.9.1"
internal const val VERSION_GIT_PUBLISH = "0.3.3"
internal const val VERSION_KTLINT = "0.34.2"
internal const val VERSION_TRUTH = "1.0"